In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/JuliaData/CSV.jl/refs/heads/main/test/testfiles/Sacramentorealestatetransactions.csv')

In [3]:
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   street     985 non-null    object
 1   city       985 non-null    object
 2   zip        985 non-null    int64
 3   state      985 non-null    object
 4   beds       985 non-null    int64
 5   baths      985 non-null    int64
 6   sq__ft     985 non-null    int64
 7   type       985 non-null    object
 8   sale_date  985 non-null    object
 9   price      985 non-null    int64
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.5+ KB

In [7]:
df.describe()

,zip,beds,baths,sq__ft,price,latitude,longitude
count,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000
mean,95750.697462,2.911675,1.776650,1314.916751,234144.263959,38.607732,-121.355982
std,85.176072,1.307932,0.895371,853.048243,138365.839085,0.145433,0.138278
min,95603.000000,0.000000,0.000000,0.000000,1551.000000,38.241514,-121.551704
25%,95660.000000,2.000000,1.000000,952.000000,145000.000000,38.482717,-121.446127
50%,95762.000000,3.000000,2.000000,1304.000000,213750.000000,38.626582,-121.376220
75%,95828.000000,4.000000,2.000000,1718.000000,300000.000000,38.695589,-121.295778
max,95864.000000,8.000000,5.000000,5822.000000,884790.000000,39.020808,-120.597599

In [5]:
df.shape

(985, 12)

Find the number of the columns in the data frame

In [27]:
num_columns = df.shape[1]
print(num_columns)

12

Find the mean of the house prices

In [28]:
mean_price = df['price'].mean()
print(mean_price)

234144.26395939087

Find the median of the house prices

In [29]:
median_price = df['price'].median()
print(median_price)

213750.0

Find the different types of property in the dataset

In [31]:
property_types = df['type'].unique()
print(property_types)

['Residential' 'Condo' 'Multi-Family' 'Unkown']

Find the maximum price of a "condo" in the dataset

In [32]:
max_condo_price = df[df['type'].str.lower() == 'condo']['price'].max()
print(max_condo_price)

360000

Find the mean price of each type of property in the dataset

In [33]:
mean_price_by_type = df.groupby('type')['price'].mean()
print(mean_price_by_type)

type
Condo           150082.185185
Multi-Family    224534.692308
Residential     239186.162486
Unkown          275000.000000
Name: price, dtype: float64

Find the count of different property types in dataset

In [35]:
count_by_type = df['type'].value_counts()
print(count_by_type)

type
Residential     917
Condo            54
Multi-Family     13
Unkown            1
Name: count, dtype: int64